# Generated by Django 5.1.2 on 2024-10-21 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badgeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('nin', models.CharField(max_length=30)),
                ('mail', models.CharField(blank=True, max_length=150, null=True)),
                ('tel1', models.CharField(blank=True, max_length=30, null=True)),
                ('tel2', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badgeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badgeur.badgeur')),
            ],
        ),
    ]
